services:
  # --- APPLICATION NEXT.JS (DEV MODE) ---
  app:
    build: 
      context: .

  # --- BASE DE DONNÃ‰ES ---
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user    
      POSTGRES_DB: db
    ports:
      - "5432:5432"          # <--- Optionnel : permet de se connecter via TablePlus/DBeaver depuis ton PC
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- ADMINER ---
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data: