services:
  app:
    build:
      context: .
      target: dev  # <--- On cible l'étape "dev" du Dockerfile
    volumes:
      - .:/app           # Synchro des fichiers locaux vers le conteneur
      - /app/node_modules # On protège les node_modules du conteneur
      - /app/.next        # On protège le dossier de build
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/lesfoulees
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lesfoulees
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: